POST http://localhost:5002/api/accounts HTTP/1.1
content-type: application/json

{
    "name": "Cash",
    "onBudget": true,
    "balance": 100
}

###

POST http://localhost:5002/api/accounts HTTP/1.1
content-type: application/json

{
    "name": "Giro",
    "onBudget": true,
    "balance": 200
}

###

POST http://localhost:5002/api/accounts HTTP/1.1
content-type: application/json

{
    "name": "Depot",
    "onBudget": false,
    "balance": 1000
}

###

POST http://localhost:5002/api/categories HTTP/1.1
content-type: application/json

{
    "name": "Miete"
}

###

POST http://localhost:5002/api/categories HTTP/1.1
content-type: application/json

{
    "name": "Einkäufe"
}

###

POST http://localhost:5002/api/categories HTTP/1.1
content-type: application/json

{
    "name": "Investments"
}

###

POST http://localhost:5002/api/transactions HTTP/1.1
content-type: application/json

{
  "transactionType": 0,
  "accountId": 2,
  "transferAccountId": null,
  "categoryId": 2,
  "date": "2022-11-15",
  "payee": "Rewe",
  "incomeType": 0,
  "amount": -20,
  "isCleared": false
}

###

POST http://localhost:5002/api/transactions HTTP/1.1
content-type: application/json

{
  "transactionType": 1,
  "accountId": 2,
  "transferAccountId": 3,
  "categoryId": 3,
  "date": "2022-11-15",
  "payee": null,
  "incomeType": 0,
  "amount": -100,
  "isCleared": false
}

###

PUT http://localhost:5002/api/transactions/7 HTTP/1.1
content-type: application/json

{
  "transactionType": 1,
  "accountId": 3,
  "transferAccountId": 2,
  "categoryId": 3,
  "date": "2022-11-15",
  "payee": null,
  "incomeType": 0,
  "amount": 100,
  "isCleared": false
}

###

GET http://localhost:5002/api/budgets/2022/11 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:5002/api/budgets/2022/11/2 HTTP/1.1
Content-Type: application/json

200

###

PUT http://localhost:5002/api/budgets/2022/11/3 HTTP/1.1
Content-Type: application/json

400

###

GET http://localhost:5002/api/accounts/2 HTTP/1.1

###

PUT http://localhost:5002/api/transactions/65 HTTP/1.1
content-type: application/json

{
  "transactionType": 1,
  "accountId": 5,
  "transferAccountId": 4,
  "categoryId": null,
  "date": "2022-11-15",
  "payee": null,
  "incomeType": 0,
  "amount": -20,
  "isCleared": true
}

###

PUT http://localhost:5002/api/transactions/6 HTTP/1.1
content-type: application/json

{
  "transactionType": 0,
  "accountId": 5,
  "transferAccountId": null,
  "categoryId": 1,
  "date": "2022-11-15",
  "payee": "Vermieter",
  "incomeType": 0,
  "amount": -50,
  "isCleared": false
}